### ISSUE TITLE
Mover este arquivo?

### ISSUE THREAD

**Issue by lucasferreira** [Mateuslh/projeto_front_end#1]
https://github.com/Mateuslh/projeto_front_end/blob/40c3002d8f6ec08bc1327c03d5e26a992c83536e/back-end/tributosV2-Spring/src/main/java/com/example/tributosV2/service/BooleanBuilderUtil.java#L11

Este arquivo não deveria estar na pasta `util` do projeto?

**Comment by mateuslh** [comment]
Olá @lucasferreira,

Realmente essa classe ficou "largada" no projeto, e com toda a certeza ela ficaria mais bem-disposta no diretório util, tendo isso em vista, o commit 8d904b1f1e7649999853e8b1c244bbe3a9693b66 resolveu esse problema.
