### ISSUE TITLE
Colocação do ENUM

### ISSUE THREAD

**Issue by lucasferreira** [Mateuslh/projeto_front_end#2]
https://github.com/Mateuslh/projeto_front_end/blob/40c3002d8f6ec08bc1327c03d5e26a992c83536e/back-end/tributosV2-Spring/src/main/java/com/example/tributosV2/model/Contribuinte/SituacaoContribuinte.java#L3

Não posso afirmar com 100% de certeza (Java não é a linguagem que eu mais trabalho) mas eu gosto da ideia de manter os ENUMS dentro das próprias classes quando eles são usados apenas na classe em si (e não em outros lugares).

Poderia ser algo tipo:

```java
public class Contribuinte extends EntityId {
  public enum situacaoType {
    ATIVO,
    DESATIVADO
  }

  @Enumerated(EnumType.STRING)
  @Column(name = "situacao", nullable = false)
  private situacaoType situacao = situacaoType.ATIVO;
```

Penso que assim fica mais fácil de manter a relação de co-relação e colocação do tipo em usos exteriores, tipo assim:

`if(Contribuinte.situacao == Contribuinte.situacaoType.ATIVO) {`

Mas enfim, pode ser só minha prática com outras linguagens que exigem a criação de "menos arquivos para pouca coisa".

**Comment by mateuslh** [comment]
Olá @lucasferreira,

Obrigado pela sugestão de mover o enum SituacaoContribuinte para dentro da classe Contribuinte. Entendo a ideia, mas acredito que manter o enum separado é mais adequado. Aqui estão os motivos:

- Reutilização: O enum pode ser útil para outros cadastros, não apenas para Contribuinte. Mantê-lo separado facilita essa reutilização e promove consistência.
- Organização: Seguindo boas práticas, é melhor manter cada classe e enum focados em suas próprias responsabilidades.
- Manutenção: Alterações no enum são feitas em um único lugar, o que simplifica a manutenção e reduz a chance de erros.
- Escalabilidade: Manter enums separados torna o código mais modular e escalável.( E torna o enum global)

Entretanto, concordo que a nomenclatura pode ser melhorada. Sugiro renomear para SituacaoCadastro, para indicar que pode ser usado por outros cadastros. 
____
Exemplo de como ficaria a alteração: 
![image](https://github.com/Mateuslh/projeto_front_end/assets/91639503/7a3a3751-6c84-41de-8c19-0979b3dfa3e1)

**Comment by lucasferreira** [comment]
Perfeito @Mateuslh 

Quem sabe então apenas `Situacao` ou `Status` para esse enum, assim usarias `Status.ATIVO` ou `Status.DESATIVADO` porque `SituacaoCadastro` da a entender que é usado só em "Cadastros" quando na verdade tu pode ter outras coisas (ex: uma lista de pessoas ou débitos, debitos inativos e etc).

**Comment by mateuslh** [comment]
Obrigado pela contribuição @lucasferreira,

Executado na alteração 006f59ff006eb4b78891dbb953be6c370e37e630.
